# Generated by Django 4.2.2 on 2025-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDeCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_archivo', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('caducidad', models.DateField()),
                ('documento_reposicion', models.CharField(blank=True, max_length=100)),
                ('fecha_reposicion', models.DateField(blank=True, null=True)),
                ('numero_envio', models.CharField(blank=True, max_length=50)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
                ('ticket_salida', models.CharField(blank=True, max_length=50)),
                ('almacen_bsci', models.CharField(blank=True, max_length=50)),
                ('numero_cliente', models.CharField(blank=True, max_length=50)),
                ('etiqueta_rfid', models.CharField(blank=True, max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
